modmap:
  - name: CapsLock to Ctrl (global)
    remap:
      CapsLock: Control_L

keymap:
  - name: GNU to CUA (Chrome Only)
    application:
      only: google-chrome
    remap:
      C-a: home
      C-e: end
      M-f: C-right
      M-b: C-left
      C-p: up
      C-n: down
      C-d: delete
      C-y: C-v
      C-k: [Shift-end, C-x]
      C-u: [C-a, delete]
